PUT http://robustsfc.pl.sophia.inria.fr:8181/restconf/config/opendaylight-inventory:nodes/node/openflow:1/flow-node-inventory:table/0/flow/1/instructions/instruction/1
Accept: */*
Cache-Control: no-cache
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/yang.data+json

{
    "instruction": [
        {
            "apply-actions": {
                "action": [
                    {
                        "output-action": {
                            "output-node-connector": "openflow:1:3"
                        },
                        "order": "1"
                    }
                ]
            },
            "order": "1"
        }
    ]
}
###