PUT http://robustsfc.pl.sophia.inria.fr:8181/restconf/config/opendaylight-inventory:nodes/node/openflow:1/flow-node-inventory:table/0/flow/1
Accept: */*
Cache-Control: no-cache
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/yang.data+json

{
    "flow": {
       "priority": "1000",
       "id": "1",
       "flow-name": "Foo",
       "table_id": "0",
       "instructions": {
           "instruction": [
               {
                   "apply-actions": {
                       "action": [
                           {
                               "output-action": {
                                   "output-node-connector": "openflow:1:1"
                               },
                               "order": 0
                           }
                       ]
                   },
                   "order": 0
               }
           ]
       }
   }
}

###